In [2]:
import numpy as np


In [3]:
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

my_array

array([1, 2, 3, 4, 5])

In [4]:
print(f"Shape of my_array: {my_array.shape}")
print(f"Data type of my_array: {my_array.dtype}")

Shape of my_array: (5,)
Data type of my_array: int64


In [6]:
my_2d_array = np.array([[1,2,3],[4,5,6]])

print(f"Shape of my_2d_array: {my_2d_array.shape}")

Shape of my_2d_array: (2, 3)


In [7]:
element = my_2d_array[0, 1]  # Accessing the element at row 0, column 1
print(f"Element at (0, 1): {element}")

Element at (0, 1): 2


In [8]:
first_row = my_2d_array[0, :]
print(f"The first row is {first_row}")  # Accessing the first row

The first row is [1 2 3]


In [9]:
third_column = my_2d_array[:, 2]  # Accessing the third column
print(f"The third column is {third_column}")


The third column is [3 6]


In [10]:
print("original Array:")
print(my_2d_array)

added_array = my_2d_array + 10  # Adding 10 to each element
print("Array after adding 10:")
print(added_array)

original Array:
[[1 2 3]
 [4 5 6]]
Array after adding 10:
[[11 12 13]
 [14 15 16]]


In [11]:
vector = np.array([100, 200, 300])

broadcast_add = my_2d_array + vector  # Broadcasting the vector to add to each row
print("Array after broadcasting addition:")
print(broadcast_add)


Array after broadcasting addition:
[[101 202 303]
 [104 205 306]]
